[project]
name = "oelm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "groq>=0.16.0",
    "ipykernel>=6.29.5",
    "markdown>=3.7",
    "pydantic>=2.10.6",
    "rich>=13.9.4",
]
